"""Type stubs for the zcash_uri package."""

from typing import Optional, Union

__version__: str

class Zip321Error(Exception): ...
class ParseError(Zip321Error): ...
class InvalidBase64Error(Zip321Error): ...
class MemoTooLongError(Zip321Error): ...
class TooManyPaymentsError(Zip321Error): ...
class TransparentMemoError(Zip321Error): ...
class RecipientMissingError(Zip321Error): ...
class InvalidPaymentError(Zip321Error): ...
class InvalidAddressError(Zip321Error): ...

class AddressInfo:
    is_valid: bool
    address_type: str
    can_receive_memo: bool
    pools: list[str]
    def __repr__(self) -> str: ...

class Payment:
    def __init__(
        self,
        recipient_address: str,
        amount_zatoshis: Optional[int] = None,
        memo: Optional[Union[str, bytes]] = None,
        label: Optional[str] = None,
        message: Optional[str] = None,
    ) -> None: ...
    @property
    def recipient_address(self) -> str: ...
    @property
    def amount_zatoshis(self) -> Optional[int]: ...
    @property
    def amount_zec(self) -> Optional[float]: ...
    @property
    def memo(self) -> Optional[bytes]: ...
    @property
    def memo_text(self) -> Optional[str]: ...
    @property
    def label(self) -> Optional[str]: ...
    @property
    def message(self) -> Optional[str]: ...
    def to_dict(self) -> dict: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class TransactionRequest:
    def __init__(self, payments: list[Payment]) -> None: ...
    @staticmethod
    def from_uri(uri: str) -> "TransactionRequest": ...
    def to_uri(self) -> str: ...
    def payments(self) -> dict[int, Payment]: ...
    def total_zatoshis(self) -> Optional[int]: ...
    def total_zec(self) -> Optional[float]: ...
    def to_dict(self) -> dict: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

def memo_to_base64(memo: bytes) -> str: ...
def memo_from_base64(encoded: str) -> bytes: ...
def validate_address(address: str) -> AddressInfo: ...
def is_valid_address(address: str) -> bool: ...
def zec_to_zatoshis(zec: float) -> int: ...
def zatoshis_to_zec(zatoshis: int) -> float: ...
def format_zec(zatoshis: int) -> str: ...
def examples() -> str: ...
